const AUDIO_ITEMS = [
  {
    slug: 'alibaba-latest-results',
    fileName: '2026-03-20T07-35-14-839Z_阿里的最新业绩分析.mp3',
    title: '阿里的最新业绩分析',
    titleEn: 'Alibaba latest earnings breakdown',
    seriesName: '财报速听',
    seriesNameEn: 'Earnings brief',
    speaker: '业绩拆解栏目',
    speakerEn: 'Results briefing desk',
    publishDate: '2026-03-20',
    durationSeconds: 525,
    summary: '围绕阿里最新业绩、增长结构和管理层后续动作，做一轮适合通勤收听的快速拆解。',
    summaryEn: 'A commute-length breakdown of Alibaba’s latest earnings, growth mix, and the next management signals to watch.',
    tags: ['阿里', '财报', '业绩'],
    tagsEn: ['Alibaba', 'Earnings', 'Results'],
  },
  {
    slug: 'host-b-profit-for-future',
    fileName: '2026-03-20T11-59-18-376Z_Host_B_拿当下的利润去换未来_这赌注可太大了.mp3',
    title: '拿当下的利润去换未来，这赌注可太大了',
    titleEn: 'Trading current profits for the future is a huge bet',
    seriesName: 'Host B 观点速听',
    seriesNameEn: 'Host B quick take',
    speaker: 'Host B',
    speakerEn: 'Host B',
    publishDate: '2026-03-20',
    durationSeconds: 289,
    summary: '聚焦企业用当期利润换长期空间的取舍，讨论重投入战略背后的风险、赔率与管理判断。',
    summaryEn: 'A short take on using current profits to buy long-term runway, with a focus on strategic risk, payoff, and management judgment.',
    tags: ['利润', '战略', '未来'],
    tagsEn: ['Profit', 'Strategy', 'Future'],
  },
  {
    slug: 'unitree-ipo-gross-margin',
    fileName: '2026-03-21T12-13-32-725Z_60_毛利背后的_大脑_焦虑_拆解宇树科技IPO招股书.mp3',
    title: '毛利背后的“大脑”焦虑，拆解宇树科技 IPO 招股书',
    titleEn: 'The brain behind the margin: unpacking Unitree’s IPO filing',
    seriesName: '招股书拆解',
    seriesNameEn: 'IPO filing teardown',
    speaker: 'IPO 观察栏目',
    speakerEn: 'IPO watch desk',
    publishDate: '2026-03-21',
    durationSeconds: 529,
    summary: '从宇树科技招股书切入，梳理毛利变化、核心能力与扩张节奏之间的真实张力。',
    summaryEn: 'A guided reading of Unitree’s prospectus, focusing on gross margin shifts, core capabilities, and the tension behind expansion.',
    tags: ['宇树科技', 'IPO', '毛利'],
    tagsEn: ['Unitree', 'IPO', 'Margin'],
  },
  {
    slug: 'robot-minting-machine-brain-deal',
    fileName: '2026-03-21T12-59-57-055Z_把机器人干成印钞机后_那个偏科生为什么要砸20亿买个_脑子.mp3',
    title: '把机器人干成印钞机后，那个偏科生为什么要砸 20 亿买个脑子',
    titleEn: 'Why spend 2 billion on a brain after robots start printing money',
    seriesName: '机器人产业观察',
    seriesNameEn: 'Robotics industry watch',
    speaker: '机器人商业化栏目',
    speakerEn: 'Robotics business desk',
    publishDate: '2026-03-21',
    durationSeconds: 569,
    summary: '围绕机器人商业化后的下一步补链动作，讨论为什么资本会重金押注“脑子”而不是继续堆硬件。',
    summaryEn: 'A look at why capital shifts from hardware to “brains” once robotics commercialization starts to work.',
    tags: ['机器人', '并购', 'AI'],
    tagsEn: ['Robotics', 'M&A', 'AI'],
  },
]

export function getLocalAudioLibrary() {
  return AUDIO_ITEMS
}
